rootProject.name = "ambassador"
include(":ambassador-storage")
include(":ambassador-commons")
include(":ambassador-application")
include(":ambassador-model")
include(":ambassador-gitlab")
include(":ambassador-gitlab-client")
include(":ambassador-document-analyzer")
include(":ambassador-fake-source")
include(":ambassador-advisor")
