spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

ambassador:
  security:
    enabled: true
    cors:
      allowedOrigins:
        - http://localhost:8080
        - http://localhost:8000
    allowedRedirectUris:
      - http://localhost:8000/projects