#ambassador:
#  source:
#    name: gitlab
#    url: <source_url>
#    token: <token>
#    system: gitlab
#    clientId: <oauth2_client_id>
#    clientSecret: <oauth2_secret>
#  source: # fake source
#    name: gitlab
#    url: https://fake.com
#    token: fake
#    system: fake
