ambassador:
  openapi:
    title: The Ambassador API
    contact:
      name: Mateusz Filipowicz
      url: https://github.com/Roche
    license:
      name: Apache-2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.txt

springdoc:
  api-docs:
    groups:
      enabled: true