apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "indexer.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "indexer.labels" . | nindent 4 }}
data:
  application-datasource.yml: |
    {{- include "database.yml" . | nindent 4 }}
  application-source.yml: |
    ambassador:
      source:
        name: gitlab
        url: https://fake
        token: fake
        system: fake
