apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "indexer.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "indexer.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels: {{- include "indexer.selectorLabels" . | nindent 6 }}